development:
  adapter: postgresql
  database: trendz
  username: postgres
  password:

test:
  adapter: postgresql
  database: trendz_test
  timeout: 5000
  username: postgres
  password:

production:
  adapter: postgresql
  database: trendz
  timeout: 5000
  username: postgres
  password: 
