development:
  host: localhost
  adapter: postgresql
  database: trendz_development
  username: postgres
  password:

test:
  host: localhost
  adapter: postgresql
  database: trendz_test
  timeout: 5000
  username: postgres
  password:

production:
  host: localhost
  adapter: postgresql
  database: trendz
  timeout: 5000
  username: postgres
  password: 
